- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import vpc_varaible
      include_vars: var/aws_vpc
    - name: creating VPC
      ec2_vpc_net:
          name: "{{vpc_name}}"
          cidr_block: "{{vpcCdir}}"
          region: "{{region}}"
          dns_support: yes
          dns_hostnames: yes
          state: "{{state}}"
          tenancy: default
      register: vpcout

    - debug:
           var: vpcout
    - name: crating Subnet
      ec2_vpc_subnet:
          state: "{{state}}"
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{region}}"
          az: "{{zone1}}"
          cidr: "{{PubSub1Cdir}}"
          map_public: yes
          tags:
            Name: Aws_pubsunet1
      register: Aws_pubsunet1




