---
- name: Setup Vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: import VPC setup variable
      include_vars: vars/output_vars
    - name: import vprofile setup variable
      include_vars: vars/vprostacksetup
    - name: Create vprofile ec2 key
      ec2_key:
                name: vprokey
                region: "{{region}}"
      register: vprokey_out

    - name: Save private key into file bastion-key.pem
      copy:
                content: "{{vprokey_out.key.private_key}}"
                dest: "./loginkeypro.pem"
                mode: 0600
      when: vprokey_out.changed
    - name: crate security group for Loadbalancer
      ec2_group:
        name: vproELB-sg
        description: allow all on port 80
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
      register: vproELB-sg_out

    - name: crate security group for Loadbalancer
      ec2_group:
             name: vproStack-sg
             description: allow all on port 22
             vpc_id: "{{vpcout.vpc.id}}"
             region: "{{ region }}"
             purge_rules: no
             rules:
               - proto: tcp
                 from_port: 80
                 to_port: 80
                 group_id: "{{vproELB-sg_out.group_id}}"
               - proto: tcp
                 from_port: 22
                 to_port: 22
                 group_id: "{{BastionSGid}}"
       register: vproStack-sg_out

